### ISSUE TITLE
Unable to output public_dns/public_ip value when requesting spot instances 

### ISSUE THREAD

**Issue by vithursant** [vithursant/terraform-aws-spotgpu#1]
Adding the snippet below to the `outputs.tf` file:
```sh
output "public-dns" {
  value = ["${aws_spot_instance_request.aws_dl_custom_spot.*.public_dns}"]
}


output "ssh-cmd" {
  value = ["${format("ssh -i %s%s.pem ubuntu@%s", var.ssh-key-dir,
    aws_spot_instance_request.aws_dl_custom_spot.*.key_name,
    aws_spot_instance_request.aws_dl_custom_spot.*.public_dns)}"]
}
```

Results in the following error when executing the command `terraform apply`:

```sh
* output.public-ip: Resource 'aws_spot_instance_request.aws_dl_custom_spot' does not have attribute 'public_dns' for variable 'aws_spot_instance_request.aws_dl_custom_spot.*.public_dns'
* output.ssh-cmd: Resource 'aws_spot_instance_request.aws_dl_custom_spot' does not have attribute 'public_dns' for variable
```

This issue is linked to https://github.com/terraform-providers/terraform-provider-aws/issues/4313.

**Comment by dennisobrien** [comment]
I had the same issue.  I added `wait_for_fulfillment = true` to the `resource "aws_spot_instance_request" "aws_dl_custom_spot"` section and it seems to have fixed it.  Can you try adding that and let us know if it fixed it for you?

**Comment by dennisobrien** [comment]
By the way -- thanks for this working example project!  It saved me a lot of time.

**Comment by vithursant** [comment]
No problem @dennisobrien I will close this issue now.
